apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: flux-system
type: Opaque
stringData:
  accesskey: minioadmin
  secretkey: minioadmin
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: kratix-bucket
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  bucketName: kratix-bucket
  endpoint: minio.kratix-platform-system.svc.cluster.local:80
  insecure: true
  secretRef:
    name: minio-credentials
---
# Single Kustomization watching bucket root (Destination uses path: / with mode: none)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kratix-workloads
  namespace: flux-system
spec:
  interval: 5s
  prune: false
  sourceRef:
    kind: Bucket
    name: kratix-bucket
  path: ./

