# ArgoCD Application for Kratix Foundry Promises
#
# Deploys the Kratix Promises (FoundryInstance and FoundryLicense) and
# the standby page infrastructure from the kratix-foundry repository.
#
# Add this file to your argo-cd repository: github.com/you-randomly/argo-cd

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix-foundry-promises
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/you-randomly/kratix-foundry.git
    targetRevision: main
    path: deploy/production
    
  destination:
    server: https://kubernetes.default.svc
    # Promises are cluster-scoped, namespace here is just for kustomization context
    namespace: kratix-platform-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
